### ISSUE TITLE
Jobs stay in the batch even after they complete

### ISSUE THREAD

**Issue by jsierles** [drfeelngood/resque-batched-job#22]
Quite often I'll find one or two jobs left in the batch which have completed successfully. I have to recreate them so they will finish and fire the after_batch callback.

Is there any reason this could happen? How can I debug further? Thanks!

**Comment by nonsensery** [comment]
Ha, I just encountered this as well. The problem seems to be that [`remove_batched_job`](https://github.com/drfeelngood/resque-batched-job/blob/master/lib/resque/plugins/batched_job.rb#L86) has to re-create the job string in order to remove it from the queue.

This is also problematic if a `perform` method mutates the `args` in any way, because it will prevent the job from being removed from the queue.

Instead, the batched code should hold onto the original source string and use that to remove the completed job from the queue.
